### PR TITLE
Make noarch

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Currently holding up a couple of migrations.

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
@sodre Would you mind merging this?

**Comment by sodre** [comment]
> @sodre Would you mind merging this?

Please open new pull request if you would like to become a maintainer.

**Comment by BastianZim** [comment]
Thanks!

Happy to help out if you want but upstream seems to be dead, I just opened the PR so that the migrations can pass. Since it’s noarch now, I don’t think another PR will be opened here.

**Pull request merged**
